sudo: false
env:
  - CXX=g++-4.8
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
language: node_js
node_js:
 - 8
 - 10
 - 12
script:
 - yarn install
 - yarn build
 - yarn lint
 - cd packages/mjml-parser-xml
 - yarn install
 - yarn test --debug
 - cd ../../packages/mjml-core
 - yarn test --debug
